<?php

/**
 * @file
 * Implemented hooks for lst_agldwg_block_content.
 */

use Drupal\lst_agldwg_block_content\MigrationPluginAlterer;
use Drupal\lst_agldwg_block_content\ModuleImplementsAlterer;

/**
 * Implements hook_module_implements_alter().
 */
function lst_agldwg_block_content_module_implements_alter(&$implementations, $hook) {
  ModuleImplementsAlterer::alter($implementations, $hook);
}

/**
 * Implements hook_migration_plugins_alter().
 */
function lst_agldwg_block_content_migration_plugins_alter(&$definitions) {
  MigrationPluginAlterer::alterDefinitions($definitions);
}
